### PR TITLE
fix issue #45 

### PR DESCRIPTION
**Pull request by acelan86**
#45

### CODE REVIEW

**Comment by acelan86** [comment]
ok, i will, thanks too

**Comment by acelan86** [comment]
i see， and i seems commit some file no necessary， so i close this pr & create new again for clearly?

**Comment by WebReflection** [comment]
listen, I've made your life easier.  I've [just pushed](https://github.com/WebReflection/document-register-element/commit/ab4c34d2533033d49a1c5dd888d94747b6e9a29b) `0.5.3` which includes your test and fixes the problem in a better way (it does not need to create two arrays so it uses same amount of memory and it's faster)

screenshot from 2015-12-04 09-22-58

**Comment by acelan86** [comment]
thank u!

**Comment by WebReflection** [comment]
thank you for the report. This was a silly mistake I shouldn't have done. Classic splice side-effect that got me like a noob :-)

**Pull request closed without merging**
