### PR TITLE
Suppress asynchronous insertion events and externalize activation method 

### PR DESCRIPTION
**Pull request by opinel**
The native implementation of the Custom-Elements spec is based on immediate instantiation of components. As the current polyfill is based on asynchronous Mutation Observers, it would be great to allow for activating the components synchronously to match the native experience. This would require the developer to make an extra call after adding a new custom element to the DOM, but would allow for a more consistent cross-browser life-cycle. Further, the DOM manipulation is still testable in a "synchronous-way".
These commits allow for providing options to the polyfill to e.g. disable the insertion events. Moreover, they are externalizing the executeAction method for the specific "attached" use-case.

### CODE REVIEW

**Comment by WebReflection** [comment]
to be honest I don't understand these changes, neither why these are needed. This polyfill has been tested and used in production and respects native behavior ... right ? I don't want to customize it in any way because that would make it not a polyfill anymore but a library ... right ?

**Comment by einarq** [comment]
The polyfill is great, but the async init is a bit painful. Also the fact that the dom elements have to be added to the dom in order for the init to be called. This is also different from native, and makes testing harder. If these changes add a simple workaround to those issues I support them, but understand that you want to keep the polyfill as close to native as possible.

**Comment by WebReflection** [comment]
there is no async init. When you register your element, you have your custom element behavior. What am I missing?

**Comment by einarq** [comment]
The createdCallback is async, so I have to emit a custom event to know when I can start working with it from the outside. Mentioned in this issue, there is a jsfiddle there as well:
https://github.com/WebReflection/document-register-element/issues/4

**Comment by WebReflection** [comment]
> the dom elements have to be added to the dom in order for the init to be called

I could go as dirty as hell and overwrite all DOM methods that deal with nodes so that as soon as anything is created, even offline, will be parsed.

That being said (and no is the answer, I won't do that) if you use `document.createElement` you should have the behavior you expect, right? Truth is that dealing with non live nodes is something somehow out of the euqation in my opinion, but I understand there should be a way to deal with that too ...

My point is that I don't want callbacks or options that have nothing to do with the polyfill intent. It is possible to trigger a part all the needed logic through a wrap or a library, but that should happen somewhere else, IMO.

I am giving a presentation about this, so far, rock solid and slick polyfill, that never gave me troubles so eventually whatever change it needs must be tested in all devices I've tested, it must have real DOM tests in place, and I need to find time to test all of that.

Apologies but when I've read the custom method to explicitly setup something I've seen red lights all over ... if that's something truly needed for the real-world code, then the polyfill should take care of it (but again, I really think I shouldn't be that obtrusive on the DOM)

**Comment by WebReflection** [comment]
@einarq your fiddle is broken (security gotchas via github and the response type that is text) but I've answered to that already anyway: https://github.com/WebReflection/document-register-element/issues/4#issuecomment-53398385

Why would I change my mind today?

**Comment by einarq** [comment]
Who knows, new arguments perhaps. Anyway, do what you want, it's your polyfil. Just voicing my support for what I thought this pull request is addressing. 
Thanks

**Comment by opinel** [comment]
Thanks for the discussion. My intend was to handle multiple ways to init the component. I agree that people could use document.createElement to already have a synchronous initialization. However, there are multiple other ways to create / manipulate DOM elements, e.g. `$('...').append('<my-custom-element />')`, Handlebars-templates or Angular templates. In all cases, the developer is expecting the element to have all its custom logic from the start, like in a native environment. 
When I am adding an element to the DOM, I might want to manipulate its children or attribute, right afterwards. Or I want to check its correct display in a unit-test. However, for both scenarios I have to wait for an asynchronous initialization that would require me to rewrite all my view code or at least my tests. 
If I would expose the synchronous helper method, it would give me the tooling to ensure that the components are active from the start.

**Comment by WebReflection** [comment]
> When I am adding an element to the DOM, I might want to manipulate its children or attribute, right afterwards.

you should use `createdCallback` which is there to exactly full-fill your needs and unit tests won't be a good excuse to make the polyfill obtrusive since either you mock the entire DOM, and you won't have any problem, or you need to test the real behavior, which is through the `createdCallback`

Sorry, but as explained in the mentioend #4 bug, I am not planning to overwrite native `innerHTML`, specially if the reason is that your test environment does not cope well with asynchronous code.

I think I am going to reject this pull request, apologies for any inconvenient but please bear in mind it's not about being "my polyfill" but it's about making this polyfill as correct as possible and less obtrusive than alternatives. Feel free to use Polymer if that solves all your problems.

Best Regards

**Comment by WebReflection** [comment]
P.S. if flicking on MutationObservers is yout problem, make the component non visible via CSS and on `createdCallback` change this condition. You need to place the custom element in the DOM regardless in order to have proper unit read because dimensions depends on lively resolved CSS.

You won't ever have a good read of anything if outside the DOM ... also you can always trigger the event after whatever you do.

Instead of asking to put a non-standard callback in this polyfill, simply trigger the same handler that the polyfill relies whenever **you** want to trigger that. It will make your execution synchronous.

I'll comeback with a live example

**Comment by WebReflection** [comment]
so, looking at the code:

```js

function forceCustomElementsSetup() {
  document.dispatchEvent(new CustomEvent('readystatechange'));
}

// later on ... do your changes and ...
forceCustomElementsSetup();

```

how doe that look like? ( yeah, it's a hack, as it was this pull request compared to standard API )

Does this solve the proble,?

**Comment by WebReflection** [comment]
and this is for @einarq , using your [same fiddler](http://jsfiddle.net/mt06sykv/3/) but including this poly from the cdn ( https://cdnjs.cloudflare.com/ajax/libs/document-register-element/0.1.6/document-register-element.js ) and writing this instead:

```js

function forceCustomElementsSetup() {
  document.dispatchEvent(new CustomEvent('readystatechange'));
}

document.registerElement('sd-editfield', {
    prototype: Object.create(HTMLElement.prototype, {
        foo: {
            value: function () {
                return "foo";
            }
        },
        createdCallback: {
            value: function () {
                console.log('createdCallback');
                this.innerHTML = "<input />";
            }
        }
    })
});

document.getElementById("placeholder").innerHTML = "<sd-editfield></sd-editfield>";
forceCustomElementsSetup();
var field = document.querySelector("sd-editfield");
console.log("before", field.foo, field.createdCallback);
setTimeout(function () {
    console.log("after", field.foo(), field.createdCallback);
});

```

The output will be:

```
"createdCallback"
"before" function () function ()
"after" "foo" function ()
```

instead of 
```
"before" undefined undefined _display:44:0
"createdCallback" _display:35:16
"after" "foo" function ()
```

which was indeed a bad and inconsistent result in Firefox ( it was good in Chrome anyway )

So, problem solved without changing anything in this poly which is still lightweight and not as obtrusive as others. You are free to play the dirty card whenever you think it's needed.

**Comment by opinel** [comment]
Too bad. But thanks for the discussion.
I am neither interested in using the polymer polyfilling libraries, nor do I want to change the spec, but I want to enable as many developers – with their existing code-bases – being able to create predictable custom-elements.
The last use-case you were describing for @einarq was exactly what the change was all about. Nobody wants to write `setTimeout` when calling  custom-element functionality. Calling the mentioned `forceCustomElementsSetup` method yields the same results as the pull-request, but the loop won't be scoped to the children of a rootNode.

**Comment by WebReflection** [comment]
I've shown a way to avoid the need for the `setTimeout` and explained how to avoid problems through CSS if the glitch is a problem. If an element wasn't there, using `createdCallback` to set-it up and make it visible should be the same.

**However**, since I am the first maniac about performance, I've got your point so I've made a [very little change here](https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.max.js#L452) enabling you or anyone that knows what is doing to perform this instead:

```js

function forceCustomElementsSetup(target) {
  (target || document).dispatchEvent(
    new CustomEvent('readystatechange'),
    {bubbles: true}
  );
}

```

This gives you the ability to confine the `querySelectorAll` query inside a single container and avoid usage of custom API and "too much magic" inside this polyfill.

Would this work? Or you still want to have a hybrid poly instead?

**Comment by opinel** [comment]
I think this would work.

**Comment by WebReflection** [comment]
good, so now the next step is to enable it through `innerHTML` and, eventually, `outerHTML`

```js
(function (gOPD) {
  if (gOPD) {
    var
      el = document.createElement('div'),
      proto = el,
      descriptor
    ;
    do {
      descriptor = gOPD(proto, 'innerHTML');
    } while (
      !descriptor &&
      (proto = Object.getPrototypeOf(proto))
    );
    if (proto && proto !== el) {
      return Object.defineProperty(
        proto,
        'innerHTML',
        {
          get: function () {
            return descriptor.get.call(this);
          },
          set: function (html) {
            descriptor.set.call(this, html);
            this.dispatchEvent(
              new CustomEvent(
                'readystatechange',
                {bubbles: true}
              )
            );
          }
        }
      );
    }
  }
  throw new Error('no way to make this work');
}(Object.getOwnPropertyDescriptor));
```

Opera throws an error here, it sets the `innerHTML` as own property during element initialization and with a misleading descriptor, so does **Chrome** or at least **Chromium** for Linux.

See why I don't want to introduce fragile, non tested, solutions but at the end of the day I've offered a way for libraries to eventually trigger that synchronous check per container instead? That woud always work, even with Opera or Chromium!

**Comment by opinel** [comment]
Agree. `innerHtml` overrides probably open a can of worms.

**Pull request closed without merging**
