### PR TITLE
Use setImmediate instead of requestAnimationFrame

### PR DESCRIPTION
**Pull request by developit**
I noticed the queue operations for enhancing elements are bound to paint timings because they use `requestAnimationFrame`. This can be brutal for performance: http://jsperf.com/raf-vs-setimmediate

This PR swaps out the underlying delay for a simple `setImmediate` method that uses the browser's asynchronous image `error` event to attempt to invoke a function as soon as possible, rather than during the next paint.

Perhaps it might be worth a quick check to see if this simple `setImmediate()` implementation is truly async, and when it isn't fall back to `setTimeout(fn, 10)`.

### CODE REVIEW

**Comment by WebReflection** [comment]
I'm afraid this PR won't probably ever land for the following reasons:

  1. I really don't use rAF just to ask something asynchronous, I use it to boost up internally as much as possible the whole logic involved if there are elements to resolve in the array
  2. using networks errors to shim any functionality is a very problematic approach if you are under CSP or restricted environment where that might not even fire.

The best part of this poly is its "universal compatibility" and unless you have numbers for the real world where setImmediate, which AFAIK doesn't try to optimize code,  is better than rAF and rAF is the bottleneck, I might consider using it only if asynchronous and going rAF as fallback for every other case.

Thanks in anyway for pointing this out, I will keep it in mind if necesary. Until that time, I rather play it safe here.

Best Regards

**Comment by WebReflection** [comment]
P.S. to avoid misunderstanding: I am not asking you benchmarks about setImmediate VS rAF, I'd like to see a Web App done via this polyfill that goes much faster using setImmediate. Anything else is a potentially problematic premature optimization I'm not fund to introduce.

**Comment by developit** [comment]
`requestAnimationFrame` does not try to optimize code. It executes a given function during the next repaint. You are only using it in one place, which is to defer upgrading of registered custom elements so that setting innerHTML does not synchronously instantiate them.

**Comment by WebReflection** [comment]
> requestAnimationFrame does not try to optimize code. It executes a given function during the next repaint.

which is exactly what I want to do, possibly fit into one single repaint all nodes that needs to show up.

I like how you ignored CSP problems ;-)

Playing dirty with the network to simulate something I don't wactually want to, doesn't look like the best way to go.

Do you have any real-world case where this hack is needed beside a micro-bench?

Thank you

**Pull request closed without merging**
