### PR TITLE
Added an example of x-clock with React.

### PR DESCRIPTION
**Pull request by trusktr**

### CODE REVIEW

**Comment by trusktr** [comment]
Yep, I haven't tried in IE8. I just copied the x-clock example. How might I test in IE8 (considering I don't have Windows on my machine right now)?

I also put up the demo here: http://trusktr.io:3237/x-clock-react.html

**Comment by WebReflection** [comment]
yeah it doesn't work, I've just tried ( from Linux ... all you need is VirtualBox or similar and a [VM image](https://dev.windows.com/en-us/microsoft-edge/tools/vms/linux/) )

So since I'm pretty sure React won't work there, and neither will Babel, just please drop those IE8 related parts, thanks.

**Comment by trusktr** [comment]
http://netrenderer.com is pretty cool! It worked in IE9, but as you confirmed, it rendered nothing in IE8.

I (gladly) removed those parts. I personally have no intention of supporting anything lower than IE11 (maybe even Edge) in my personal projects. x]

**Comment by trusktr** [comment]
By the way, the reason I made this demo was to prove that a DOM manipulation library like React works with custom elements, which in turn shows that the concept behind [A-Frame](https://aframe.io) (which uses Custom Elements) is awesome, and that we can make a 3D scene using any DOM helper like React, Mithril, Mercury, Om, CitoJS, etc.

**Comment by WebReflection** [comment]
Yeah, it's good that this polyfill is not obtrusive and it works well with also not so obtrusive technologies ;-)

**Comment by WebReflection** [comment]
Thanks. I've published [this demo too in the test page](http://webreflection.github.io/document-register-element/test/examples/x-clock-react.html)

**Comment by trusktr** [comment]
Sweet :+1:

**Pull request merged**
