### PR TITLE
Patch attachShadow to observe Shadow DOM

### PR DESCRIPTION
**Pull request by ryansolid**
Browsers which have native Shadow DOM support, but not native Custom Element support (like Safari 10) cause the polyfill not to work when attaching Custom Elements to Shadow Roots. This fix only patches Shadow DOM v1 syntax and is an adaption of the technique used by https://github.com/webcomponents/custom-elements.

### CODE REVIEW

**Comment by WebReflection** [comment]
P.S. thanks for the PR though, the proposed improvement seems reasonable. If you don' have time or don't know how to test or improve this PR let me know and I'll try to bring your requirements in.

Best Regards

**Comment by treshugart** [comment]
> The descriptor is potentially obtrusive because it's not configurable and not writable.

This has affected us in the past with separate polyfills. Definitely an issue.

**Comment by ryansolid** [comment]
Alright as I said I basically just was looking for a fix for the issue and went over to the other polyfill and lifted it. I have made the changes as to the request although admittedly just running PhantomJS I can't actually confirm the test works.  

As for the descriptor I just dropped it, as I honestly don't know what the preferred way to handle it is, although I will say I've only been using it with skatejs-named-slots which works but I can't speak to any other Shadow DOM polyfills.

Beyond this I will probably need assistance if anything else needs updating to fulfill the pull request.  Thank you.

**Comment by WebReflection** [comment]
It looks good, thanks. I will merge and double test this evening in the supported list of browsers and, if OK, I'll publish.

To test browsers you can just type `npm run web` and check via the shown link

**Comment by WebReflection** [comment]
v1.2.0 has more or less these fixes in.

There were globals leaking on tests and few other things I wanted to improve so ... nothing personal, I hope it works for your needs now.

**Comment by ryansolid** [comment]
No problem thank you. Sorry for any unneeded additional effort on your part.

You're completely right I didn't even see it. My Javascript is a bit rusty thanks to developing almost exclusively in Coffeescript for the past 4 years. After debugging a ton of JS but writing CS one tends to mentally ignore certain parts of the language since it has no bearing on the solution (as written in CS).

**Pull request closed without merging**
