### PR TITLE
updated .after file to set window to the context instead of doing not…

### PR DESCRIPTION
**Pull request by mmclau14**
changed the var.after file so that i could be plopped into a build system and build for whatever window it was currently being executed for. (useful when dealing with multiple windows)

### CODE REVIEW

**Comment by mmclau14** [comment]
realized that i needed to do it for all the other files.

**Comment by WebReflection** [comment]
OK, `innerHTML` might indeed be broken after last changes but I wonder why instead of fixing just that you are modifying all other templates?

**Comment by mmclau14** [comment]
sorry? i did not know that innerhtml was broken. all of the tests passed for me when i built. i may be a bit confused regarding how to actually use this shim, but i do know, that in order for this to work in the middle of a larger script or in environments with a different than default setup, the this keyword should be used so that at least something can be understood from the context rather than a variable that may or may not exist

**Comment by WebReflection** [comment]
The build folder is the one that contains scripts:
https://github.com/WebReflection/document-register-element/tree/master/build

If you use the node module, it uses `global` already:
https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.node.js#L1423

If you use the regular DOM env, it passes window because it's global too.

When you use `this` you are doing nothing different than using `window` because you'll expect all other things retrieved per realm (`Object`, `document`, etc) to be in that context .

On AMD builds the context might be asynchronous and not bound to a `use strict` executed function so `this` would break while `window` won't.

There are no environment where `window` is not available but `this` is, since we are talking about a DOM related polyfill, so while `this` can be ambiguous, `window` never is (beside the node module that uses `global` indeed).

Accordingly, since this polyfill has always worked on production, I was wondering why instead of adjusting the only file that indeed has problems due latest changes, you decided that `this` was a better choice.

Since like I've explained, this is not actually necessarily the case, I was thinking maybe you had some issue but AFAICT the only issue you had was with the `innerHTML` file, right?

In such case I won't accept this PR as is because it does a bit too much.

Please confirm `innerHTML` was the only issue, thank you.

**Comment by WebReflection** [comment]
Actually, now that I look at files in src ... what is again the problem here?
Maybe I misunderstood this PR entirely ... I don't see any error in the current build.

Also you shouldn't edit build files directly, these get overwritten every time I publish new versions.

**Comment by WebReflection** [comment]
P.S. if your goal is to install the script in an iframe, like Google AMP is doing already, you might want to use the official approach `require('document-register-element').installCustomElements(window)`

**Comment by mmclau14** [comment]
that's ok. i didn't notice problems with innerhtml either. for me, all 39 tests worked. i committed any changes that were made by myself plus any changes that the build process made (by running: make) this was so i could make sure that all of the tests were still running. the build files were not excluded with a gitignore so i assumed they were part of the commit. do you have instructions regarding how you would like pull requests done somewhere? maybe i missed it. but regarding your other point about async environments not working, if you would be so kind as to open the code on my next comment, you will see that browsers do indeed ser the context if the context is not already bound on the callback passed into the async methods of settimeout and raf.

**Comment by mmclau14** [comment]
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <link rel="stylesheet" href="">
</head>
<body>
    <script>
        setTimeout(function (argument) {
            console.log(this);
        });
        requestAnimationFrame(function () {
            console.log(this);
        });
    </script>
</body>
</html>
```

**Comment by mmclau14** [comment]
i am loading in these scripts without the use of requires and have to expand their use to multiple iframes below the single one they are loaded from.

**Comment by WebReflection** [comment]
You said you have problems with your build process, I say you can have problems with `this` with other build processes too.

`setTimeout(function(){'use strict';(function(){console.log(this)}())});`

That one logs `undefined`

If any 3rd parts wrapper execute this code outside the global scope there's no gian, just a bet, on what the `context` will be and it won't solve any problem at all cross realm because if you have `window` reference on the top level script of an iframe, that is the global window of that iframe.

`this` in nodejs is the module itself, it can be anything ... `window` can, and should be never ambiguous.

So I'll ask again> what real-world problem are you trying to solve?

**Comment by mmclau14** [comment]
fair enough. goodbye

**Pull request closed without merging**
