### PR TITLE
stringify first argument passed to createElement

### PR DESCRIPTION
**Pull request by kof**
I have stumbled over a bug caused by a different component which has passed undefined to createElement. It is wrong to support it, but as browser vendors do stringify first argument a polyfill should also do.

I haven't managed to create/run tests properly as I had difficulties to understand how it works. Please feel free to add a test :)

### CODE REVIEW

**Comment by WebReflection** [comment]
This made you discover a bug ...are you sure you want it fixed? If you register twice 'undefined' it's going to throw an error regardless. As a developer, do you prefer knowing about bugs earlier or later?

**Comment by kof** [comment]
Its just creating an undefined tag, works in browser. Bug can be discovered by observing dom tree. I think its better to stick with browser implementation, checked this behaviour in chrome, ff, safari.

**Comment by opinel** [comment]
Isn't this rather a bug report for Chrome?

**Comment by kof** [comment]
no idea how it is specified, but it seems like chrome, safari and firefox all agreed upon this.

**Comment by WebReflection** [comment]
I actually read `registerElement` instead of `createElement` ... let me check the code ...

**Comment by WebReflection** [comment]
OK, I was in the middle of something so I've fixed this for you in `0.1.9` together with `jshint` validation. Hope that's OK

**Comment by kof** [comment]
thanks :+1:

**Pull request closed without merging**
